SELECT SUM(ORD_AMOUNT) FROM Orders;



SELECT SUM(ORD_AMOUNT) FROM Orders
WHERE ORD_DATE = "2008-11-01";



SELECT ORD_DATE, SUM(ORD_AMOUNT) FROM Orders
GROUP BY ORD_DATE;


SELECT ORD_DATE, SUM(ORD_AMOUNT) AS Total  FROM Orders
GROUP BY ORD_DATE
ORDER BY Total ASC;


SELECT ORD_DATE, SUM(ORD_AMOUNT) FROM Orders
GROUP BY ORD_DATE
ORDER BY SUM(ORD_AMOUNT) ASC
LIMIT 3;


select * from Orders
limit 10 offset 10;